### ISSUE TITLE
Fix images in README.md

### ISSUE THREAD

**Issue by spy4x** [spy4x/seed#103]
Images of Angular and Prisma are missing (broken link probably).
Please find alternative URLs and replace them.

<img width="226" alt="Screen Shot 2022-11-16 at 21 10 19" src="https://user-images.githubusercontent.com/4995814/202189332-49de3157-5629-4264-adbe-c244c1e28b30.png">

**Comment by anhbaonguyenle** [comment]
Hi bro, angular logo in line 29 use this URL "https://angular.io/assets/images/logos/angular/angular.svg" and
Prisma logo in line 60 use URL "https://seeklogo.com/images/P/prisma-logo-3805665B69-seeklogo.com.png"

**Comment by schamiir** [comment]
I'm new to Open Source and would love to work on this!

**Comment by spy4x** [comment]
Hey guys @anhbaonguyenle @schamiir !
Thank you! Feel free to create a Pull Request - I will be happy to merge 👍🙂

**Comment by anhbaonguyenle** [comment]
I've fixed your readme.md, check it out. This is my first time participating in the Open Source community, I'm happy to help you

**Comment by spy4x** [comment]
Thank you for your PRs @anhbaonguyenle @Phuong150922 !
You made them almost at the same time, so I merged both, taking one image from one PR and a second from another :D

**Comment by spy4x** [comment]
Hey @schamiir !
You wanted to participate. This issue is fixed, but there is a similar quick one if you are interested:
https://github.com/spy4x/seed/issues/107

Also, I'm going to prepare many more, but code-related ones. Angular / Nest.js / Docker.
Anything you are interested in particular - let me know :)

**Comment by spy4x** [comment]
@anhbaonguyenle @schamiir @Phuong150922 Hey guys! Could I ask you how did you find this project?
I'm excited of new people coming and want to know where you came from :)

**Comment by anhbaonguyenle** [comment]
i find this project from "https://goodfirstissues.com/"

**Comment by spy4x** [comment]
@anhbaonguyenle Interesting :) Thanks!
